# Generated by Django 3.1.1 on 2020-09-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_auto_20200102_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
